### ISSUE TITLE
Please, update to support react 18

### ISSUE THREAD

**Issue by progdog-ru** [davidcalhoun/react-hover-slideshow#14]

**Comment by Moizsohail** [comment]
+1

**Comment by davidcalhoun** [comment]
Thanks, sorry for the delay!  I'll try to update this when I get a chance!  Also happy to accept PRs.

**Comment by davidcalhoun** [comment]
React 18 support has now been added, supported from [v3.0.0](https://github.com/davidcalhoun/react-hover-slideshow/releases/tag/v3.0.0)!
